# you should install pyyaml

# config.py ------------------------------------------------------------
# model checkpoint (only one at a time)

#grpo - 40steps
# ckpt: ysc0034/my-vl-checkpoint

#grpo - 180steps
# ckpt: ysc0034/grpo_tools_180steps

#grpo - 135steps
# ckpt: ysc0034/grpo_135steps


#more checkpoints (sft)
#tt
# ckpt: ysc0034/sft_tool_thinker_0p1

#1nl
# ckpt: ysc0034/sft_tools_nl_0p1

#3nl
# ckpt: ysc0034/sft_tools_nl_0p3_wo_pose

#3nlo
# ckpt: ysc0034/sft_tools_nl_0p3_w_orien

#ttmul
ckpt: ysc0034/sft_tools_thinker_multitools


# model.py ------------------------------------------------------------
# turn on the debug mode for moure detailed output
debug: True
# 设置临时存储文件的地址
# 命名规范：{checkpoint名字}_{数据集名称|实验性质（test or run）}
sandbox_temp_img_folder: ./0_mmstar_test
# under project root, dont start with /
local_temp_img_folder: yangshucheng-compass/0_mmstar_test


# mmstar database (only one at a time) ------------------------------------------------------------
# if use full = true, use the 500-sample full size mmstar dataset
# otherwise use the 5-sample mmstar test dataset
use_full: False


# only true when test the baseline Qwen2.5_VL_7B_Instruct w.o. code ----------------------------------------
# keep it false
use_origin: True

