# you should install pyyaml

# config.py ------------------------------------------------------------
# model checkpoint (only one at a time)

#grpo - 40steps
# ckpt: ysc0034/my-vl-checkpoint

#grpo - 180steps
# ckpt: ysc0034/grpo_tools_180steps

#grpo - 135steps
# ckpt: ysc0034/grpo_135steps

# puco80
# ckpt: ysc0034/grpo_pure_code_spatial457_w_think_80

# puco90
# ckpt: ysc0034/grpo_pure_code_spatial457_wo_multireward_90

# puco100
ckpt: ysc0034/exp_pure_code_spatial457_w_code_len_100steps

# pucot100
# ckpt: ysc0034/exp_pure_code_spatial457_w_code_think_len_100steps


#more checkpoints (sft)
#tt
# ckpt: ysc0034/sft_tool_thinker_0p1

#1nl
# ckpt: ysc0034/sft_tools_nl_0p1

#3nl
# ckpt: ysc0034/sft_tools_nl_0p3_wo_pose

#3nlo
# ckpt: ysc0034/sft_tools_nl_0p3_w_orien

#ttmul
# ckpt: ysc0034/sft_tools_thinker_multitools

#q2ttmul
# ckpt: ysc0034/sft_qwen2_tools_thinker_multitools


# model.py ------------------------------------------------------------
# turn on the debug mode for moure detailed output
# 有事没事都设置为True
debug: True
# 设置临时存储文件的地址
# 命名规范：{checkpoint名字}_{数据集名称|实验性质（test or run）}
sandbox_temp_img_folder: ./0_mmstar_test
# under project root, dont start with /
local_temp_img_folder: yangshucheng-compass/0_mmstar_test


# mmstar database (only one at a time) ------------------------------------------------------------
# if use full = true, use the 500-sample full size mmstar dataset
# otherwise use the 5-sample mmstar test dataset
# 正式跑结果都设为True, 测试的时候设置为False
use_full: True

# only true when test the baseline Qwen2.5_VL_7B_Instruct w.o. code ----------------------------------------
# keep it false
# 这个是控制模型不适用sandbox，而采用原版推理，只有对原版模型without code测试时候需要开启，其他测试设为False
use_origin: True

# spatial457.py -------------------------------------------------------------
# 如果在MMStar上测试，那么保持这个选项为True, 在Spatial457系列上测试，如果测试的是原版模型（0shot, without code， 那么设置为False, 其余情况设置为True）
# 针对Spatial457数据集的prompt构造方法，如果想使用原版，那么mini_flag设置为False
# 如果在测Omni3d,请无论什么模型一直保持True
mini_flag: False

